[build]
  publish = ".next"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true